//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Births
    {
        public int id { get; set; }
        public Nullable<int> n_piglets { get; set; }
        public string date { get; set; }
        public Nullable<int> weaning { get; set; }
        public string fem_code { get; set; }
        public Nullable<int> parameter { get; set; }
        public string status { get; set; }
    }
}
