//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.DatabaseFirst
{
	using System;

	public partial class Females
	{
		public string code { get; set; }
		public string birthday { get; set; }
		public string status { get; set; }
		public Nullable<int> martenity { get; set; }
		public Nullable<int> user { get; set; }
		public Nullable<int> misbirths { get; set; }
	}
}
