//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parameters
    {
        public int id { get; set; }
        public string died_pigs { get; set; }
        public Nullable<int> lived_pigs { get; set; }
        public Nullable<int> mummy_pigs { get; set; }
    }
}
