//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class PigGroups
    {
        public int id { get; set; }
        public string name { get; set; }
        public string weaning_date { get; set; }
        public Nullable<double> weigth_avg { get; set; }
        public Nullable<double> second_avg { get; set; }
        public Nullable<int> pig_count { get; set; }
        public Nullable<int> died_pigs { get; set; }
        public Nullable<int> user { get; set; }
    }
}
